# -*- coding: utf-8 -*-
"""emotions_model_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFw7PnQ6WkjzVNjoik4OOy1ZHsvqMmXn
"""

import pickle
import numpy as np
import tensorflow
import keras

# loading the data from pickle :
with open('/content/images.p', 'rb') as f:
    x = pickle.load(f)

with open('/content/labels.p', 'rb') as f:
    y = pickle.load(f)

print ('Images:',x.shape)
print ('Labels:',y.shape)

# labelEncoding output
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

y

# Standardizing the images for CNN Model:
x = x/255
x= x.reshape(-1,48,48,1)   # -1 -> the total number of images in x variable, 1 -> Number of channel in gray scale, 48,48 -> image shape

# Using one-hot encoding to output column:
from keras.utils import to_categorical
y = to_categorical(y)   # Don't run it multiple times.

# Splitting Training and testing datas    ( IF THE MODEL NOT GIVES ABOVE 50% ACCURACY RE-RUN FROM THIS SHELL ONCE AGAIN)
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.1)  #0.1 -> 10% data for testing

print("xtrain:",xtrain.shape)
print("xtest:",xtest.shape)
print("ytrain:",ytrain.shape)
print("ytest:",ytest.shape)

# CNN Model training :
from keras.models import Sequential
from keras.optimizers import Adam
from keras.layers import Conv2D,MaxPooling2D,Flatten,Dense

model = Sequential()
# 1st Convolutional Layer:
model.add(Conv2D(50, (3, 3), input_shape=(48,48,1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# 2nd Convolutional layer:
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# 3rd Convolutional layer:
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Adding flatten Layer: converts 2D to 1D
model.add(Flatten())

# Hidden Layer:
model.add(Dense(256, activation='relu'))  # 256 number of neurones

# Output Layer:
model.add(Dense(5, activation='softmax'))
model.compile(Adam(learning_rate=0.001),loss = 'categorical_crossentropy', metrics =['accuracy'])

# Model summary printing:
model.summary()

history = model.fit(xtrain, ytrain, epochs=10, validation_data=(xtest,ytest))

# To save the model for deployment:
# .h5 -> HDF5 File format
# It stores model's optimizer's state(with learning rate), model's architecture, training configurtations, weights.
model.save('Emotion_detection_model.h5')
print("Model Saved")

